export const LOAD_ALL_TWEETS = "LOAD_ALL_TWEETS";
export const LOAD_SINGLE_TWEET = "LOAD_SINGLE_TWEET";
export const IS_LOADING_SINGLE = "IS_LOADING_SINGLE";
export const REPLY_TO_TWEET = "REPLY_TO_TWEET";
export const SERVER_FAILED_TO_RESPOND = "SERVER_FAILED_TO_RESPOND";
export const IS_LOADING_ALL = "IS_LOADING_ALL";
export const IS_LOADING_REPLY = "IS_LOADING_REPLY";
